<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-9B9M95V" failures="2" tests="7" name="Surefire test" time="2.498" errors="0" timestamp="2020-06-07T21:16:09 EDT">
  <testcase classname="com.automation.APITestFramework.testCase.CreateCustomerTest" name="invalidateCreatedCustomerAPI" time="1.126"/>
  <testcase classname="com.automation.APITestFramework.testCase.CreateCustomerTest" name="validateCreatedCustomerAPI" time="0.611"/>
  <testcase classname="com.automation.APITestFramework.testCase.CreateCustomerTest" name="validateCreatedCustomerAPI" time="0.624"/>
  <testcase classname="com.automation.APITestFramework.testCase.CreateCustomerTest" name="validateCreatedCustomerAPI" time="0.63"/>
  <testcase classname="com.automation.APITestFramework.testCase.CreateCustomerTest" name="validateCreatedCustomerAPI" time="0.635"/>
  <testcase classname="com.automation.APITestFramework.testCase.DeleteCustomerTest" name="delete_customer" time="0.651">
    <failure type="java.lang.AssertionError" message="ID key is not present in JSON response expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in JSON response expected [true] but found [false]
at com.automation.APITestFramework.testCase.DeleteCustomerTest.delete_customer(DeleteCustomerTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- delete_customer -->
  <testcase classname="com.automation.APITestFramework.testCase.DeleteCustomerTest" name="delete_customer" time="0.677">
    <failure type="java.lang.AssertionError" message="ID key is not present in JSON response expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in JSON response expected [true] but found [false]
at com.automation.APITestFramework.testCase.DeleteCustomerTest.delete_customer(DeleteCustomerTest.java:32)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- delete_customer -->
  <testcase classname="com.automation.APITestFramework.setUp.BaseTest" name="@BeforeSuite setUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase classname="com.automation.APITestFramework.setUp.BaseTest" name="@BeforeSuite setUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase classname="com.automation.APITestFramework.setUp.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="com.automation.APITestFramework.setUp.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
</testsuite> <!-- Surefire test -->
